# -*- coding: utf-8 -*-
"""Predictive_Maintenance_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dm39F--yYeZX-D9sPZJyucBnsei6UdBW
"""

!pip install pandas numpy scikit-learn matplotlib seaborn shap joblib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import joblib

from google.colab import files

uploaded = files.upload()

data = pd.read_csv("machine_data_1000_rows.csv")

data.head()

print(data.shape)

data.head(10)

print(data["status"].value_counts())

X = data[["temperature","vibration"]]

y = data["status"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("Accuracy =", accuracy*100,"%")

cm = confusion_matrix(y_test, predictions)

print(cm)

print(classification_report(y_test,predictions))

new_machine = [[70,85]]

prediction = model.predict(new_machine)

print("Machine Status =", prediction[0])

samples = [

    [30,10],
    [50,45],
    [80,90]

]

results = model.predict(samples)

for s,r in zip(samples,results):
    print(s,"=>",r)

importances = model.feature_importances_

features = X.columns

plt.figure(figsize=(6,4))
plt.bar(features, importances)

plt.title("Feature Importance")
plt.show()

joblib.dump(
    model,
    "predictive_maintenance_model.pkl"
)

from google.colab import files

files.download(
    "predictive_maintenance_model.pkl"
)

!pip install shap

import shap
import matplotlib.pyplot as plt

explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(X_test)

# Get class names from the model for better labeling
class_names = model.classes_

# Iterate through each class and plot its SHAP summary
for i, class_name in enumerate(class_names):
    print(f"SHAP summary plot for class: {class_name}")
    # For multi-class TreeExplainer, shap_values is a 3D array (n_samples, n_features, n_classes).
    # Select SHAP values for the current class 'i' across all samples and features.
    shap.summary_plot(shap_values[:, :, i], X_test.values, feature_names=X_test.columns.tolist(), show=False)
    plt.title(f"SHAP values for class: {class_name}")
    plt.show()

temp = 70
vib = 3

prediction = model.predict([[temp, vib]])

probability = model.predict_proba([[temp, vib]])

print("Prediction:", prediction[0])

print("\nProbability:")

for cls, prob in zip(model.classes_, probability[0]):
    print(f"{cls}: {prob*100:.2f}%")

import matplotlib.pyplot as plt

importance = model.feature_importances_

features = ["Temperature", "Vibration"]

plt.figure(figsize=(6,4))
plt.bar(features, importance)

plt.title("Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance Score")

plt.show()

!pip install shap

import shap

explainer = shap.TreeExplainer(model)

sample = pd.DataFrame({
    "temperature":[70],
    "vibration":[3]
})

shap_values = explainer.shap_values(sample)

shap.initjs()

# Assuming we want to plot for the predicted class, which is 'Failure' (index 0)
# You can choose a different class index if you want to visualize for other classes
class_index = 0

shap.force_plot(
    explainer.expected_value[class_index],    # Base value for the chosen class
    shap_values[0, :, class_index],           # SHAP values for the first sample, all features, for the chosen class
    sample.iloc[0]                            # The features for the first sample as a Series
)

temp = 70
vib = 3

prediction = model.predict([[temp, vib]])[0]

print("Prediction:", prediction)

if temp > vib:
    print("Reason: Temperature is the major contributor.")
else:
    print("Reason: Vibration is the major contributor.")

print(f"Temperature = {temp}")
print(f"Vibration = {vib}")

import gradio as gr

def predict(temp, vib):

    prediction = model.predict([[temp, vib]])[0]

    probs = model.predict_proba([[temp, vib]])[0]
    confidence = max(probs) * 100

    if prediction == "Healthy":
        reason = """
🟢 Machine Status: HEALTHY

✅ Temperature is within safe limits.
✅ Vibration is stable.
✅ No abnormal machine behavior detected.

Recommendation:
Continue normal operation.
"""

    elif prediction == "Warning":
        reason = """
🟡 Machine Status: WARNING

⚠ Temperature is increasing.
⚠ Vibration indicates possible wear.

Recommendation:
Schedule preventive maintenance.
"""

    else:
        reason = """
🔴 Machine Status: FAILURE

🚨 Temperature exceeds safe operating limits.
🚨 Abnormal vibration detected.

Recommendation:
Immediate inspection required.
"""

    return f"""
Prediction: {prediction}

Confidence: {confidence:.2f}%

Temperature: {temp} °C
Vibration: {vib}

{reason}
"""

demo = gr.Interface(
    fn=predict,

    inputs=[
        gr.Slider(20, 100, label="Temperature (°C)"),
        gr.Slider(0, 100, label="Vibration Level")
    ],

    outputs=gr.Textbox(
        label="AI Analysis Dashboard",
        lines=15
    ),

    title="🏭 AI Predictive Maintenance System",

    description="""
Enter machine temperature and vibration values.
The AI model predicts machine health and provides maintenance recommendations.
"""
)

demo.launch()

"""Machine Health **Distribution**"""

import matplotlib.pyplot as plt

data['status'].value_counts().plot(kind='bar')

plt.title("Machine Health Distribution")
plt.xlabel("Status")
plt.ylabel("Count")

plt.show()

"""Temperature Distribution"""

plt.figure(figsize=(8,5))

plt.hist(data['temperature'], bins=20)

plt.title("Temperature Distribution")
plt.xlabel("Temperature")
plt.ylabel("Frequency")

plt.show()

"""Vibration Distribution"""

plt.figure(figsize=(8,5))

plt.hist(data['vibration'], bins=20)

plt.title("Vibration Distribution")
plt.xlabel("Vibration")
plt.ylabel("Frequency")

plt.show()

"""Feature Importance"""

importance = model.feature_importances_

features = ["Temperature","Vibration"]

plt.figure(figsize=(6,4))

plt.bar(features, importance)

plt.title("Feature Importance")

plt.show()

"""Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test,predictions)

plt.figure(figsize=(5,5))

plt.imshow(cm)

plt.colorbar()

plt.xticks([0,1,2],model.classes_)
plt.yticks([0,1,2],model.classes_)

plt.title("Confusion Matrix")

plt.show()

"""Temperature vs Vibration Scatter Plot"""

plt.figure(figsize=(8,6))

for status in data['status'].unique():

    subset = data[data['status']==status]

    plt.scatter(
        subset['temperature'],
        subset['vibration'],
        label=status
    )

plt.xlabel("Temperature")
plt.ylabel("Vibration")

plt.title("Temperature vs Vibration")

plt.legend()

plt.show()

"""SHAP Explainability Graph"""

import shap
import matplotlib.pyplot as plt

explainer = shap.TreeExplainer(model)

# shap_values will be a 3D array for multi-class classification: (n_samples, n_features, n_classes)
shap_values_3d = explainer.shap_values(X_test)

# Convert the 3D shap_values array into a list of 2D arrays (one for each class)
# This is the format shap.summary_plot expects for multi-class plots
shap_values_list = [shap_values_3d[:, :, i] for i in range(shap_values_3d.shape[2])]

# Get feature names from X_test columns
feature_names = X_test.columns.tolist()

# Plot the summary. shap.summary_plot will automatically handle the list of SHAP values for multi-class.
shap.summary_plot(
    shap_values_list,
    X_test.values, # Pass X_test as a numpy array
    feature_names=feature_names,
    class_names=model.classes_, # Provide class names for better labels
    show=True # Ensure plot is displayed
)

"""Failure Probability Dashboard Graph"""

sample = [[70,50]]

prob = model.predict_proba(sample)[0]

plt.figure(figsize=(6,4))

plt.bar(
    model.classes_,
    prob
)

plt.title("Failure Probability")

plt.ylabel("Probability")

plt.show()

"""Correlation Heatmap"""

import pandas as pd

df_numeric = data.copy()

df_numeric['status'] = df_numeric['status'].map({
    'Healthy':0,
    'Warning':1,
    'Failure':2
})

corr = df_numeric.corr()

plt.figure(figsize=(6,5))

plt.imshow(corr)

plt.colorbar()

plt.xticks(range(len(corr.columns)), corr.columns, rotation=45)
plt.yticks(range(len(corr.columns)), corr.columns)

plt.title("Correlation Matrix")

plt.show()

